local Plug = vim.fn['plug#']
vim.call('plug#begin', '~/.local/share/nvim/plugged')

Plug('junegunn/vim-plug')
Plug('vim-airline/vim-airline')
Plug('vim-airline/vim-airline-themes')
Plug('nanotech/jellybeans.vim')
Plug('w0rp/ale')
Plug('scrooloose/nerdcommenter')
Plug('sjl/gundo.vim')
Plug('godlygeek/tabular')
Plug('easymotion/vim-easymotion')
Plug('haya14busa/incsearch.vim')
Plug('haya14busa/incsearch-easymotion.vim')
Plug('othree/html5.vim')
Plug('wincent/command-t', {['do'] = 'cd ruby/command-t/ext/command-t && ruby extconf.rb && make'})
Plug('mhinz/vim-grepper')
Plug('tpope/vim-fugitive')
Plug('fatih/vim-go')
Plug('tpope/tpope-vim-abolish')
Plug('qpkorr/vim-bufkill')
Plug('Shougo/unite.vim')
Plug('Shougo/vimfiler.vim')
Plug('ryanoasis/vim-devicons')
Plug('neoclide/coc.nvim', {['branch'] = 'release'})
Plug('MattesGroeger/vim-bookmarks')
Plug('pangloss/vim-javascript')
Plug('mxw/vim-jsx')
Plug('HerringtonDarkholme/yats.vim')
Plug('luochen1990/rainbow')
Plug('rhysd/vim-clang-format')
Plug('guns/xrm-color-table.vim')
-- Depency for v-icd
Plug('guns/vim-sexp',   {['for'] = 'clojure'})
Plug('junegunn/fzf', {['do'] = vim.fn['fzf#install']})
Plug('liquidz/vim-iced', {['for'] = 'clojure'})
Plug('liquidz/vim-iced-coc-source', {['for'] = 'clojure'})
Plug('guns/vim-clojure-static')
Plug('guns/vim-clojure-highlight')
Plug('eraserhd/parinfer-rust', {['do'] = 'cargo build --release'})
Plug('tpope/vim-rhubarb')
Plug('mg979/vim-visual-multi', {['branch'] = 'master'})
Plug('tpope/vim-obsession')
Plug('bakpakin/fennel.vim')
Plug('hashivim/vim-terraform')
Plug('github/copilot.vim')

vim.call('plug#end')

